### ISSUE TITLE
Text cut on Galaxy Note8

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX#1]
From user words:

> When in the DEX and clicking on the Receive coin; next to KMD and Bitcoin it states: "Click to create an orc"

> Also on my Note 8 I noticed when creating a password and didn't have a special character that I needed, there was a warning in red below that telling me what I needed for that password, but it didn't state the entire paragraph. I think it ended with something like" ....a lower ca..." it ended with those three dots.

Will try to find Note8 or similar model emulator and reproduce

**Comment by tonymorony** [comment]
![image](https://user-images.githubusercontent.com/24797699/61260131-ba52fa80-a785-11e9-82c5-a059931572ed.png)

Issue was in screen resolution selector, text cut in HD (1480x720) mode

**Comment by Kiruel** [comment]
noted thanks.
