### ISSUE TITLE
Paste address on SEND field

### ISSUE THREAD

**Issue by dudezmobi** [KomodoPlatform/atomicDEX#102]
AtomicDex 0.2.0
Android

PASTE context menu does not appear during sending funds to other wallet

0. Copy RECEIVER wallet address
1. Open atomic dex
2. Open wallet
3. Choose any ASSET
4. Choose SEND 
5. Input MAX value
6. PASTE receiver address
7. Erase receiver address (simulate there is a mistake, use backspace)
8. PASTE receiver address again, PASTE context does not appear

**Comment by tonymorony** [comment]
Thank you for the report.
Pasting problems in some cases / to some fields is known issue at the moment (there are some glitches in Flutter framework as far as I know). It'll be fixed in future releases from our or framework side.

**Comment by dth88** [comment]
@tonymorony I have not experienced any paste issues in the recent updates on both platforms, should we close this one?

**Comment by tonymorony** [comment]
It should be fixed since we've updated flutter with this issue resolution included https://github.com/flutter/flutter/issues/37798
closing this one
