### ISSUE TITLE
[Usability] Unlock Funds error display closes quickly

### ISSUE THREAD

**Issue by dudezmobi** [KomodoPlatform/atomicDEX#106]
Error display closes quickly, users have not finished reading the error message yet.

**Comment by tonymorony** [comment]
Thank you for the issue.
Now this message is displaying for a 3 seconds. How do you think - what is the optimal non-annoying time?

**Comment by dth88** [comment]
@tonymorony did we do something regarding this issue? or is it still pending?

**Comment by tonymorony** [comment]
We've increased time this message appear, closing this one
