### ISSUE TITLE
[Usability] Japan language suggestion

### ISSUE THREAD

**Issue by dudezmobi** [KomodoPlatform/atomicDEX#108]
Japanese users requested to add 日​本​語 in laguages

**Comment by Cris-F** [comment]
I believe that the app has been translated into Japanese already.
I have experienced one user (live) not be able to use Japanese.  There phone was set to Japanese.
Will investigate.
@dudezmobi where did you see the Japanese user request?

**Comment by dudezmobi** [comment]
its on IOS native language is japanese, IOS ipad A1474. no japanese language selection and the screen eventhough is english

**Comment by Cris-F** [comment]
OK, I'll try today on android. Maybe @tony, @gcharang or someone can check out the tech when they have a chance.

**Comment by tonymorony** [comment]
Japanese language is not added yet. I'm closing this issue since there is already one related to translations implementation: https://github.com/KomodoPlatform/atomicDEX/issues/69
@ca333 fyi: there are multiple requests for Japanese language translaton ^^
