### ISSUE TITLE
[Android] Version 0.2.1 Doesn't Open

### ISSUE THREAD

**Issue by whitmorekevinj** [KomodoPlatform/atomicDEX#110]
After updating to version 0.2.1 from 0.2.0 the app only shows a black screen when opened. My device is a Pixel 2 XL running Android 10.

I've tried forcing the app closed and opening it again, as well as restarting the phone with no luck.

**Comment by gcharang** [comment]
hey, the issue is known. there were a few backward incompatible upgrades. a clean reinstall should fix the issue. make sure to backup your seed phrase

**Comment by whitmorekevinj** [comment]
Yep, that did the trick. Thanks.
