### ISSUE TITLE
REL amount incorrect in orderbook after deleting decimals of already selected BASE coin when creating new order

### ISSUE THREAD

**Issue by lilszi** [KomodoPlatform/atomicDEX#113]
How to Replicate:

Select any coin to trade (base) that has decimals in the amount you have, put max volume

Select the coin you want to receive (rel) , don't select from orderbook, but press create order, enter any amount

Now go back and delete the decimals of the base coin and press Trade

Order will be pushed to the orderbook with an insanely large or a much smaller number for the REL coin that you did set. 

Example: 
BASE: 59.9216431 
HUSH REL:  1 BTC 
go ahead and delete .9216431 of the end from HUSH , place order, in orderbook now it shows 
59 HUSH <> 3481 BTC

**Comment by tonymorony** [comment]
Thank you for the report! 
That is very dangerous/bad case.
Issue was reproduced and forwarded to developers team.

**Comment by tonymorony** [comment]
@lilszi bug was isolated and fixed. Patched version will be available in approx 1-2 days

**Comment by tonymorony** [comment]
fixed in 0.2.5
