### ISSUE TITLE
Wrong sorting of orders

### ISSUE THREAD

**Issue by garnon** [KomodoPlatform/atomicDEX#126]
Usually, the orders in atomicDEX are sorted by descending price, meaning the best offer is right at the top. However, in some circumstances (not reproducable, but see attached screenshot), a worse price is listed at the top, breaking a proper sorting by descending price.

This is dangerous since some users will always pick the top offering assuming it's always the best offering they can get, and they might get financially wrecked by a totally unrealistic price.

![order_sorting](https://user-images.githubusercontent.com/25053375/68761441-54cc2900-0614-11ea-92ce-8b00ddad7225.png)

**Comment by garnon** [comment]
Here's another example. Notice the descending price sorting with the exeption of the top entry:
![wrong_sorting2](https://user-images.githubusercontent.com/25053375/68938187-20847400-079e-11ea-8b09-72bff6d93554.png)

**Comment by garnon** [comment]
Looks like the price "0.01" is causing a sorting problem, as can be seen both examples?

**Comment by SirSevenG** [comment]
Much thanks for report, reproduced.

**Comment by tonymorony** [comment]
This one was fixed in 0.2.14
