### ISSUE TITLE
Impossible to view one's order in the context of other orders

### ISSUE THREAD

**Issue by garnon** [KomodoPlatform/atomicDEX#127]
Let's say I have only KMD in my atomicDEX wallet and want to trade it for ETH. Let's say I'll look at the available orders and decide that the offers do not satisfy me. So I decide to create an order myself and want to see "the other way round" which offerings there are already, so what would be a reasonable price for me to offer. So I return to the trade tab, pretend I would sell ETH for KMD (where in reality I want to do it the other way round), just to see the order book. At this point, the app doesn't allow me to do so already since I don't have ETH yet.

Ok, so let's assume I just want to pick my own imaginary price then. So I create an order myself, enter my desired amounts and confirm to create the order. At least then I want to be able to see my created order in the context of the other orders, in other words – where my "blind guess" has put me in the total ranking of all orders, or if there are other orders at all, who knows? So I tap on the order to see it in the context of all the other orders. But too bad: nothing happens.

**Comment by SirSevenG** [comment]
Thanks for feedback.
I believe addition of general orderbook, as mentioned in #87 will fix it.
It is planned for future releases.

**Comment by tonymorony** [comment]
Thats available since 0.2.14
