### ISSUE TITLE
Show more infomration about ongoing swap

### ISSUE THREAD

**Issue by damascene** [KomodoPlatform/atomicDEX#137]
I think it would be useful to have more verbose output from the swapping process. 
Currently it shows "swap onging" 0/3 1/3 2/3 3/3 
This can give a little insight on what is going on, why it's taking long at one stage and what issue that caused a failure if it happens.

I suggest as an example something like this:

- matching orders
- partner got disconnected (failure)
- waiting for confirmation on your transaction (txid this)
- waiting for confirmation of the partner transaction (txid that)

so it will give you some insight while waiting on how much to wait or what caused the failure. It could be another window for the detail so you keep it simple.

**Comment by tonymorony** [comment]
Thank you for your suggestion and issue creating! 👍 

It was implemented so I'm closing this one

![paste (2)](https://user-images.githubusercontent.com/24797699/82739185-c1647500-9d67-11ea-84bd-891643af95a1.png)
