### ISSUE TITLE
5 digits input issue base sell

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX#2]
From user words:

> when trying to sell DOGE for BTC, when entering Amount to Sell, it only allows me 4 digits. When I hit the 5th digit, the whole string erases. I can't actually enter enough DOGE to satisfy the BTC minimum amount (0.0077 BTC, or roughly 27200 DOGE)
> I can confirm a succesful DOGE for KMD sale, though 

Will try to reproduce, at the moment don have any 5 digits balance

**Comment by Kiruel** [comment]
Because he probably don't have enough balance DOGE.

**Comment by ca333** [comment]
please try to reproduce - i can provide 5 digit amounts for testing

@tonymorony @Kiruel

**Comment by nasbats** [comment]
![20190718_174637](https://user-images.githubusercontent.com/35640832/61490870-4b8fc000-a984-11e9-99eb-c2827e9d000f.gif)
Screencap video of issue. Sorry for potato, but it's the result of stacking 3 free apps to capture, trim, and convert to a format I could upload.

**Comment by tonymorony** [comment]
Thank you for video! Working exactly same way on my side.

adb: [5digs.txt](https://github.com/KomodoPlatform/atomicDEX/files/3409724/5digs.txt)

![videoissue](https://user-images.githubusercontent.com/24797699/61513957-5a6b8680-aa07-11e9-9b69-a503f7955847.gif)

**Comment by Kiruel** [comment]
Its because you don’t have enough RICK. So if you try to put more than your balance the field is clean.

**Comment by tonymorony** [comment]
I have 11111 RICK on balance but cant input 5th digit. I wonder it's visible on gif above...

**Comment by Kiruel** [comment]
Ok I find, it's a limitation for SELLING we can remove that if needed.

**Comment by tonymorony** [comment]
1 DGB price is around 0.01$, 10000 DGB selling is just 100$ order. So it would be great if it'll be possible to input >4 digits into this field.

**Comment by Kiruel** [comment]
Ok I will fix it and remove this limitation.
