### ISSUE TITLE
Multilingual Support

### ISSUE THREAD

**Issue by Acura360** [KomodoPlatform/atomicDEX#23]
Maybe we the Community can help to give AtomicDex a Multilingual Support in the future ?

Support for the Key markets:

Russia
Indian
China
German
etc.

**Comment by ca333** [comment]
Chinese, Japanese, Korean, Spanish and Russian is arranged by our team. For other languages we would appreciate community support. I can personally cover French, German and a few other languages after the initial beta. DM me if anything is not clear.

The l10n file is located in https://github.com/KomodoPlatform/atomicDEX/blob/master/l10n.dart

**Comment by garnon** [comment]
As a native German and German teacher, I can also help with that.

**Comment by ca333** [comment]
moved to https://github.com/KomodoPlatform/atomicDEX/issues/69 
Thanks for init ticket @Acura360

**Comment by ZaferGraph** [comment]
I pulled Turkish one.
