### ISSUE TITLE
Long app startup on Android

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX#24]
start taking around 20 seconds, have quite good Wi-Fi connection, Xiaomi Redmi Note 5 phone

adb log: https://paste.ubuntu.com/p/MYXBg5yYrQ/

video: https://send.firefox.com/download/f5bf3b70d435216d/#DbYFPmTWRuCnRmnBtDS3zw

**Comment by Kiruel** [comment]
It's the normal process, mm2 need some time to start + activate all coins and get all balances.

**Comment by artemii235** [comment]
@Kiruel It's not normal for user experience. IIRC I was told that GUI should parallelize the enable requests to speed up them. Is it happening in latest version? I'm going to perform a benchmark with same coins activated in parallel and check what time it will take. I will post results here.

**Comment by Kiruel** [comment]
Yes activatate part and get balance are parallelized.

**Comment by tonymorony** [comment]
https://paste.ubuntu.com/p/Fjzg4pqxvm/ 14 coins activation and balance checking one by one (without parallelization) took 20 seconds on my side

**Comment by artemii235** [comment]
Should be fixed in https://github.com/KomodoPlatform/atomicDEX-API/commit/582352f356701dce388d7418dfbb7901b8d878bd, please test when GUI with updated MM2 is available.

**Comment by ca333** [comment]
confirm the fix with https://github.com/KomodoPlatform/atomicDEX-API/commit/582352f356701dce388d7418dfbb7901b8d878bd
