### ISSUE TITLE
tx history not displaying

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX#25]
User Oszy reports, all coins affected. 
User yorklab resolved issue with clearing data and cache (but reappears after viewing MARTY tx history). Did not resolve for Oszy. Reboot phone also not helping. 
Logs end with `18 10:49:05, common:470] CORE panic! Some("attempt to subtract with overflow")`
Version - BarterDEX MarketMaker 7fc26fff2

**Comment by Kiruel** [comment]
This one should be fix with the next release. We will keep you update.

**Comment by Cryptosaurus89** [comment]
Same issue, but for KMD and RICK tx history. Other coins are fine with me.
It does not load history. Once clicked one of these coins, every other coin does not load anymore.

Also orderbook does not load anymore after clicking one of these coins portfolio.
Looks like it's hanging in checking tx history.

App restart does fix it, until checking tx history of KMD or RICK again.

**Comment by ca333** [comment]
fixed
