### ISSUE TITLE
Typo for "name" in the i10n file may save you searching for bug one day

### ISSUE THREAD

**Issue by imylomylo** [KomodoPlatform/atomicDEX#26]
https://github.com/KomodoPlatform/atomicDEX/blob/master/l10n.dart#L144

On that line, the "name" attribute is spelled incorrectly, i guess the IDE auto checks things, but just in case you wanted to catch this before it's a hair pulling moment down the track :)

`swapSucceful` should be `swapSuccessful` but any changes need correction where it's called.   If it ain't broke.....

**Comment by ca333** [comment]
we will clean up code after init revision - typos not considered issues for now
