### ISSUE TITLE
exchange rate in USD displaying not correct when creating maker order

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX#32]
On screenshot: input for trade 0.05 ETH for 10 KMD

What means 1 KMD = 0.005 ETH rate, or 1 ETH = 200 KMD

In USD equivalent should be ~242$ (with KMD by 1.21$). So it seems this USD amount calculating not correct.

![image](https://user-images.githubusercontent.com/24797699/61527917-39fef480-aa26-11e9-8298-9a1a6efdbf98.png)

**Comment by Kiruel** [comment]
should be fix on the dev branch. @ca333

**Comment by smk762** [comment]
![ethrate](https://user-images.githubusercontent.com/35845239/61627024-5b274580-acb1-11e9-8206-ac2f97ee2c03.jpeg)

Appears to be resolved on Android (v0.1.3-a - db6ded6ec)

**Comment by tonymorony** [comment]
![image](https://user-images.githubusercontent.com/24797699/62020929-8fc56080-b1cd-11e9-8518-37fb02fbcc79.png)

calculation on order creation still working not correct in some cases @Kiruel 0.1 ETH to 25 USDC it's ~250$ ETH/USDC rate or 0.004 USDC/ETH rate (tested on 0.1.5)

**Comment by tonymorony** [comment]
fixed in `0.1.53`
