### ISSUE TITLE
[password] space in the end

### ISSUE THREAD

**Issue by bitcoinsfacil** [KomodoPlatform/atomicDEX#35]
Android 6.0 sony xperia e5 (f3311) 

When inputting the password space was added in the end

**Comment by tonymorony** [comment]
Hello @bitcoinsfacil 

Could you please elaborate a little bit:
Am I understand correct that it was encryption password?
Did this happen when you created an account or login?
How you noticed that it have additional space?

If it reproducible on your end - would be very helpful if you can record short screencast with problem.

Thank you in advance!

**Comment by bitcoinsfacil** [comment]
Will try, might be on my side but happened twice. When typing the password a final space was added into the password. 
So basically the password for encryption had a space in the end, usually they do not accept that on passwords but I might be wrong.

**Comment by ca333** [comment]
not able to reproduce
