### ISSUE TITLE
[eth qr code] not readable on metamask

### ISSUE THREAD

**Issue by bitcoinsfacil** [KomodoPlatform/atomicDEX#36]
Metamask on MAC won't read the QR code generated by the app to deposit ETH

Android 6.0 Sony Xperia E5 (f3311)

**Comment by tonymorony** [comment]
Hello @bitcoinsfacil 

I've tried another ETH wallet and QR code from it also not scanning by metamask QR reader.

Is there any wallet which working fine with metamask qr scanner on your side?

**Comment by bitcoinsfacil** [comment]
I do not use other wallets sorry @tonymorony

**Comment by ca333** [comment]
issue on metamask
