### ISSUE TITLE
[UI - eth swap] minimum trade

### ISSUE THREAD

**Issue by bitcoinsfacil** [KomodoPlatform/atomicDEX#37]
There is no input prior to deposits/trades where it shows what is the minimum trade. 

Android 6.0 Sony Xperia (f3311)

**Comment by tonymorony** [comment]
Hello @bitcoinsfacil Thank you for feedback.
Where do you think it is better to display minimal trade amount?

**Comment by ca333** [comment]
It shows minimum trade requirement as soon as you try to trade with an amount below the minimum.
