### ISSUE TITLE
[send logs] send feedback does not attach anything

### ISSUE THREAD

**Issue by bitcoinsfacil** [KomodoPlatform/atomicDEX#38]
Android 6 sony xperia e5 

Send feedback opens screen for `sharing` but doesn't attach/write anything on Discord. On telegram sends a message that says 
```
My logs for the 2019-07-22T03:54:01.280631
```

**Comment by tonymorony** [comment]
@bitcoinsfacil Could you please try to forward it to another place ("Copy to clipboard" option lets say)?

**Comment by bitcoinsfacil** [comment]
Yes, this is what I get `content://com.komodoplatform.atomicdex.flutter.share_provider/external_cache/share/log.txt`

Worked on whatsapp so I'll send that on the other issue
