### ISSUE TITLE
Orders history list empty but orders are active

### ISSUE THREAD

**Issue by lilszi** [KomodoPlatform/atomicDEX#40]
Active orders list not appearing anymore, android 0.1.3a, restarted phone and cleared cache didst help, newly created order does not appear too. Swaps are happening so the orders are active but can't be seen.

**Comment by Kiruel** [comment]
Can you share the logs here please.

**Comment by lilszi** [comment]
Sure. 
[https://pastebin.com/vvuh5miN](url)

**Comment by lilszi** [comment]
fully reinstalled the app now it's fine.

**Comment by tonymorony** [comment]
Hi! 

Aha, as I can see there was old mm2 version in this log so something doesnt update properly by play market "Update" button (we already working on updating process improvement)

Great that it work on your side now, I'm closing this issue.
