### ISSUE TITLE
Withdraw transaction history shows source address as destination if less than whole balance sent.

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX#41]
After sending funds, transaction history screen displays the AtomicDEX wallet address as the "To" address. 
Transaction: https://kmd.explorer.dexstats.info/tx/10e9b8c42182eb120774987e86e241797727a70a580007e039879d1ef4b2ba52

![Screenshot_20190723-192822](https://user-images.githubusercontent.com/35845239/61709055-e15e8d00-ad80-11e9-8b86-fb7cc79cfe81.jpg)
![image](https://user-images.githubusercontent.com/35845239/61709194-36020800-ad81-11e9-80a6-9aae9fa07aa3.png)

To confirm this is not due to the returned rewards also tested with RICK
Transaction: https://rick.explorer.dexstats.info/tx/7aabaacc7c80cb9414e48c5385b56e870982a608ad70ec416bf5660d2519f1d5
![image](https://user-images.githubusercontent.com/35845239/61709471-ee2fb080-ad81-11e9-9cbe-8e7824384f39.png)
![image](https://user-images.githubusercontent.com/35845239/61709631-38b12d00-ad82-11e9-9c7d-d9e8007ad349.png)

If sending whole balance (no unspent utxo returning), correct destination "to" address displays correctly.

![image](https://user-images.githubusercontent.com/35845239/61709730-701fd980-ad82-11e9-9748-fa9bc0386256.png)

**Comment by cipig** [comment]
The withdraw transactions are OK, you sent from RUwodWWAabv3h2jSatVDSMT89cLkTMSutA to RKD8NjuLNrnqaFY9KRpU6MAWHeve9byjAA and the rest was returned to RUwodWWAabv3h2jSatVDSMT89cLkTMSutA, that is why the tx has 2 outputs.

**Comment by smk762** [comment]
I understand, but atomicdex display doesn't show the address where bulk of funds (the address input as destination) went to.
![image](https://user-images.githubusercontent.com/35845239/61710492-5b444580-ad84-11e9-981f-2c93bcf3c6f2.png)

This creates the misconception that all funds were sent to self. User reported this when attempting to send to Binance (I linked them to tx on explorer to confirm it actually went there).

**Comment by tonymorony** [comment]
Reproduced on my side: change destination address displaying in tx history instead of recipient

**Comment by Kiruel** [comment]
Can you tell me how to reproduce please, this is a new seed ? I can't reproduce in my side.

**Comment by smk762** [comment]
Seed created in Atomicdex, prior version, then restored when updating. Device is Android, s10e.

**Comment by tonymorony** [comment]
To reproduce just send not whole balance of any UTXO based coin not to yourself. Change address (your atomicdex receiving address) will be displayed in detailed tx history in "To" field (recipient)

Video with issue reproducing (works like this in 100% cases on my side) : https://drive.google.com/file/d/1bkYG5v99RWhvBYoYIXDguquVYvAtrccz/view?usp=sharing
