### ISSUE TITLE
PIN is initialized when device reboots during account creation

### ISSUE THREAD

**Issue by rodent-test** [KomodoPlatform/atomicDEX#44]
I rebooted my phone (Android) while the app was encrypting my initial wallet and didn't seem to finish (both fast and non-fast encryption). After the reboot, the app thought I had a wallet with a PIN and asked me for the PIN, but of course I didn't know the PIN since I never got there. 

I fixed it using recover wallet (I had the seed anyway), and that worked great.

When opening the failed wallet with the passphrase (so I can try to delete it), I get stuck on "decrypting wallet".

**Comment by tonymorony** [comment]
Can confirm that in some rare cases encryption hangs and app killing causing corrupted wallet creation to which is not possible to login. It might be very helpful if you can collect adb logcat logs on this corrupted wallet login attempt.

**Comment by ca333** [comment]
if you kill phone during such a critical stage its "expected behaviour" - restoring with seed and encrypted properly resolved this issue.
