### ISSUE TITLE
No "max" option when entering swap from swipe-right context menu

### ISSUE THREAD

**Issue by rodent-test** [KomodoPlatform/atomicDEX#45]
The app (on Android) does not show the Max option in Exchange/trade when I enter that screen from the coins overview.

The max option does appear when reselecting the coin from the drop-down menu.

**Comment by tonymorony** [comment]
Thank you for report! 

Can confirm such bug. It described in this issue also: https://github.com/KomodoPlatform/atomicDEX/issues/4

**Comment by tonymorony** [comment]
@Kiruel could you please check this one? Should be not huge fix (still actual with 0.1.5)
Just use swap button on dashboard hover and "max" button will not appear on DEX page


![image](https://user-images.githubusercontent.com/24797699/62021219-d9627b00-b1ce-11e9-8e69-1090c73e00f1.png)
![image](https://user-images.githubusercontent.com/24797699/62021221-dc5d6b80-b1ce-11e9-9249-dacf6c42a491.png)

**Comment by tonymorony** [comment]
fixed in `0.1.53`
