### ISSUE TITLE
"Standard" seed restore improvement ideas

### ISSUE THREAD

**Issue by gcharang** [KomodoPlatform/atomicDEX#46]
Suggestion:

When restoring a seed phrase (not custom), instead of a single blank, it would be better to provide 12 boxes and validate the input into each box to make sure they are valid bip39 words and provide feedback after each word.

To do this, my suggestion will be to provide 12 boxes and a button that says 
 "Next box". When the button is hit, the word in the current box should be validated and if it is valid, move the cursor to the next box. If not, turn the box red and say invalid word

I believe this will make the restore process easier and less error prone. In the current process, the user needs to input spaces and it is always a struggle to keep track if 1 or more spaces are added or none are added.

**Comment by tonymorony** [comment]
There is example of seed in this field (it with spaces), also you can press on eye to type and see the  seed. Grammar checkers and manipulations with seed input is unsafe practice as far as I know + wif/some custom seed input is possible and separation here will unnecessary complicate things imo

**Comment by gcharang** [comment]
```
Grammar checkers
```
I am not suggesting a Grammar checker. Just validate the word's existence in the bip39 list

I understand there is an example shown. But checking visually if there is 1 space or two between two words is difficult in a mobile phone.

That is why I proposed a solution where spacebar is not needed.

Also, I haven't suggested manipulating the seed

**Comment by tonymorony** [comment]
There is exist seed validity checking already - if you not select "Allow custom seed" checkmark you'll not able to proceed with not valid bip39 seed

**Comment by gcharang** [comment]
Yes, the checking is there for the whole seed. User doesn't get an indication of which mistake they made
- Did they add extra spaces? How many?
- Did they make a spelling error in one word?
- more than one word?
