### ISSUE TITLE
Coin amount showing negative value during a swap

### ISSUE THREAD

**Issue by gcharang** [KomodoPlatform/atomicDEX#48]
https://discordapp.com/channels/412898016371015680/584762059430821909/604346882185101332

by user `@JvdP#8992`

![2b6ced05-80c7-4b77-8476-7c42d249a6ac](https://user-images.githubusercontent.com/21151592/61967163-51277e80-aff2-11e9-9643-8d0f00ee9223.png)

**Comment by tonymorony** [comment]
Not enough information and not clear how to reproduce it (no app version, no steps/case to reproduce, no information about swap, no app logs)
