### ISSUE TITLE
No way to create wallet without setting a password

### ISSUE THREAD

**Issue by gcharang** [KomodoPlatform/atomicDEX#49]
The description says it is possible, but there is no way to do it currently.
![img](https://user-images.githubusercontent.com/21151592/61968333-67830980-aff5-11e9-8289-4de5ad37f0f7.jpeg)

**Comment by tonymorony** [comment]
@ca333 It looks like text on this page should be updated. Sentence about "not to use password" option seems not actual. Instead some sentence about password purpose and difference from seed might be helpful on this page

**Comment by tonymorony** [comment]
text was removed in `0.1.53`
