### ISSUE TITLE
Indicate the status of funds better

### ISSUE THREAD

**Issue by gcharang** [KomodoPlatform/atomicDEX#51]
Feature request:

When making a swap, the whole amount is still shown in the wallet. Only when a user tries to move or trade funds, etc. will there be an indication

**Comment by tonymorony** [comment]
You'll not able to use funds locked in swap with relevant error print.

What is your suggestion for better indication - how it should looks like and where ?

**Comment by gcharang** [comment]
In the Portfolio screen, each coin should have two values: "Total balance" and "Balance locked in a Trade"

**Comment by ca333** [comment]
This is coming in mm2 - so there will be an additional field to flag the "reserved amount" - closing this since not dir. GUI related.
