### ISSUE TITLE
Swap still not finished after 20 minutes

### ISSUE THREAD

**Issue by dudezmobi** [KomodoPlatform/atomicDEX#54]
Swap is not yet finished 20 mins... already in 2/3. 55b33634-a849-4579-9bd1-31caf2299478. Internet connection is slow. Switched from mobile internet to wifi internet

**Comment by dudezmobi** [comment]
Timedout after 2 hours but my rick and morty are gone now.

**Comment by lilszi** [comment]
We migrated the RICK & MORTY test-chains to new and more economic smart chains with a hybrid PoW and PoS structure. AtomicDEX mobile will automatically use the new chains and thus not contain your old RICK/MORTY balances.
