### ISSUE TITLE
Timeout error lost coins

### ISSUE THREAD

**Issue by dudezmobi** [KomodoPlatform/atomicDEX#55]
Encountered timeout error and i lost all coins. Swap id. 55b33634-a849-4579-9bd1-31caf2299478

**Comment by lilszi** [comment]
Same as issue 54? Coins are "lost" because of new RICK/MORTY chains.

**Comment by ca333** [comment]
Yes - we upgraded the Rick & Morty chains so your balance will be 0. Faucets were upgraded too so you can just request new testcoins.
