### ISSUE TITLE
Android. Display problem on pin unlock on smaller devices

### ISSUE THREAD

**Issue by dudezmobi** [KomodoPlatform/atomicDEX#60]
Pin input is truncated on a 2.5 inch by 4.5 inch screen

**Comment by tonymorony** [comment]
@dudezmobi Can you provide a screenshot and device model?

**Comment by dudezmobi** [comment]
Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: TonyL <notifications@github.com> Date: 7/31/19  21:11  (GMT+08:00) To: KomodoPlatform/atomicDEX <atomicDEX@noreply.github.com> Cc: dudezmobi <christian.silvestre@dudez.mobi>, Mention <mention@noreply.github.com> Subject: Re: [KomodoPlatform/atomicDEX] Android. Display problem on pin unlock
  on smaller devices (#60) @dudezmobi Can you provide a screenshot and device model?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/KomodoPlatform/atomicDEX/issues/60?email_source=notifications\u0026email_token=AI4YR6YEUFBTVDIASNJ6QI3QCGFO5A5CNFSM4IIGIKH2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3HGFZQ#issuecomment-516842214",
"url": "https://github.com/KomodoPlatform/atomicDEX/issues/60?email_source=notifications\u0026email_token=AI4YR6YEUFBTVDIASNJ6QI3QCGFO5A5CNFSM4IIGIKH2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3HGFZQ#issuecomment-516842214",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by dudezmobi** [comment]
I have legacy units and i would have an industrial grade unit bht1800 denso wave by months end..i can test on these devicesSent from my Samsung Galaxy smartphone.
-------- Original message --------From: TonyL <notifications@github.com> Date: 7/31/19  21:11  (GMT+08:00) To: KomodoPlatform/atomicDEX <atomicDEX@noreply.github.com> Cc: dudezmobi <christian.silvestre@dudez.mobi>, Mention <mention@noreply.github.com> Subject: Re: [KomodoPlatform/atomicDEX] Android. Display problem on pin unlock
  on smaller devices (#60) @dudezmobi Can you provide a screenshot and device model?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/KomodoPlatform/atomicDEX/issues/60?email_source=notifications\u0026email_token=AI4YR6YEUFBTVDIASNJ6QI3QCGFO5A5CNFSM4IIGIKH2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3HGFZQ#issuecomment-516842214",
"url": "https://github.com/KomodoPlatform/atomicDEX/issues/60?email_source=notifications\u0026email_token=AI4YR6YEUFBTVDIASNJ6QI3QCGFO5A5CNFSM4IIGIKH2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3HGFZQ#issuecomment-516842214",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by dudezmobi** [comment]
![2019-08-01 07 41 59](https://user-images.githubusercontent.com/37325051/62255472-e03bf880-b42f-11e9-997f-6898071810fe.jpg)

this is on the lower end samsung unit

**Comment by Kiruel** [comment]
But you can still unlock your the application ? Witch device do you have exactly ? Can you prodive a screenshot without the 'Ringtone' please.
