### ISSUE TITLE
App version is not visible

### ISSUE THREAD

**Issue by dudezmobi** [KomodoPlatform/atomicDEX#61]
Latest update does not show app build anymore.

**Comment by tonymorony** [comment]
@dudezmobi Do you mean version print on "Settings" page? Also Is it Android or iOS and could you please provide a screenshot?

**Comment by ca333** [comment]
@dudezmobi log out and log in - let us know if it shows the version afterwards

**Comment by dudezmobi** [comment]
Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: TonyL <notifications@github.com> Date: 7/31/19  21:14  (GMT+08:00) To: KomodoPlatform/atomicDEX <atomicDEX@noreply.github.com> Cc: dudezmobi <christian.silvestre@dudez.mobi>, Mention <mention@noreply.github.com> Subject: Re: [KomodoPlatform/atomicDEX] App version is not visible (#61) @dudezmobi Do you mean version print on "Settings" page? Also Is it Android or iOS and could you please provide a screenshot?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/KomodoPlatform/atomicDEX/issues/61?email_source=notifications\u0026email_token=AI4YR67BLRNYL7IEXDBTW43QCGF23A5CNFSM4IIGQBU2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3HGOWA#issuecomment-516843352",
"url": "https://github.com/KomodoPlatform/atomicDEX/issues/61?email_source=notifications\u0026email_token=AI4YR67BLRNYL7IEXDBTW43QCGF23A5CNFSM4IIGQBU2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3HGOWA#issuecomment-516843352",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ca333** [comment]
delete the application and reinstall it - the update process without prior deinstallation seems "unclean" - fixed in next version
