### ISSUE TITLE
Android. Encrypting wallet takes too long on the new version

### ISSUE THREAD

**Issue by dudezmobi** [KomodoPlatform/atomicDEX#64]
Previous version registration and new wallet creation is fast. Latest version is relatively and exponentially slower.

**Comment by ca333** [comment]
It is a hashing process and it takes some time. You can chose the fast encryption method (insecure) if your phone model takes too long.

**Comment by dudezmobi** [comment]
1 hour and still not yet.finished.

**Comment by dudezmobi** [comment]
This is a performance issue on general phones. My test unit now is a low end general public use android mobile unit

**Comment by dudezmobi** [comment]
Confirmed ticket closed
