### ISSUE TITLE
[UX] - Canceling an order should not reset the UI

### ISSUE THREAD

**Issue by nymkappa** [KomodoPlatform/atomicDEX#65]
## Issue
At the swap confirmation screen, clicking on cancel should not reset the previous view.

## Step to reproduce

1. Setup you swap at the `Exchange` view
<img src="https://user-images.githubusercontent.com/9780671/62255212-319bb600-b437-11e9-9f48-628b82fa62a3.jpg" alt="drawing" width="200"/>

2. At the confirmation screen, press `CANCEL`
<img src="https://user-images.githubusercontent.com/9780671/62255230-3eb8a500-b437-11e9-8443-a33dfb21231c.jpg" alt="drawing" width="200"/>

3. All swap inputs have been cleared in the `Exchange` view, so I have to type them again (annoying)
<img src="https://user-images.githubusercontent.com/9780671/62255251-51cb7500-b437-11e9-8397-e491c1d066b9.jpg" alt="drawing" width="200"/>

## Expected behavior
When pressing `CANCEL` at step 2. The `Exchange` view is shown again, with previously input parameter, as show in step 1.

**Comment by dth88** [comment]
@jorisvial thanks for your input, we are currently re-thinking the UX, we will look into this for sure.
