### ISSUE TITLE
No repopulation of fields -->> misleading price data - when selecting from orderbook list where maker amount is less than the amount I was seeking to take

### ISSUE THREAD

**Issue by 11allbits** [KomodoPlatform/atomicDEX#67]
1.  I select to sell 11 kmd
2.  From the "select coin" dropdown i hit "click to see 3 orders" for VRSC
3.  On the list that comes up, the best priced maker offer is for an amount far less than 11 KMD - I decide I want to take that order anyway, so I click it
4.  I click it and am taken back to the main "EXCHANGE" page - the VRSC amounts have been populated properly.  BUT, the KMD amount did not get correlatively adjusted - it remains at 11 KMD
5.  At the bottom of that page,misleading pricing data is generated (suggesting that I'm trading at 1 VRSC=1.46...KMD.  This is very far from the price I selected (because the wrong KMD volume is being used to generate this information, I suspect)
6.  I decide not to go through with the swap because I can't get comfortable that I'm getting the price I selected.

Four screenshots of the workflow for this are attached

![Screenshot_20190801-063204](https://user-images.githubusercontent.com/38767863/62313621-14baaf00-b446-11e9-800d-eaaebd164bc7.jpg)
![Screenshot_20190801-063127](https://user-images.githubusercontent.com/38767863/62313628-18e6cc80-b446-11e9-8474-e624ed2979dd.jpg)
![Screenshot_20190801-063118](https://user-images.githubusercontent.com/38767863/62313634-1dab8080-b446-11e9-809b-24af072aeb11.jpg)
![Screenshot_20190801-063110](https://user-images.githubusercontent.com/38767863/62313637-20a67100-b446-11e9-98a1-25ebaa0d402e.jpg)

**Comment by tonymorony** [comment]
thank you for your report!
such base coin field adjustment was added in `0.1.53`
