### ISSUE TITLE
[l10n] add multilingual support

### ISSUE THREAD

**Issue by ca333** [KomodoPlatform/atomicDEX#69]
To add further languages plz use https://github.com/KomodoPlatform/atomicDEX/blob/master/l10n.arb on https://translate.google.com/toolkit and translate it to the desired languages.

Language coverage

- [x] Chinese traditional
- [x] Chinese simplified
- [x] Russian
- [ ] Indian
- [x] German
- [x] Japanese
- [x] French
- [ ] Korean
- [ ] Hebrew
- [ ] Spanish
- [ ] Italian
- [ ] Arabic

**Comment by dth88** [comment]
closing this in favor of #151
