### ISSUE TITLE
App crashes in iOS when I pull down my control center

### ISSUE THREAD

**Issue by himu007** [KomodoPlatform/atomicDEX#7]
On iOS
1. Start app
2. Login
3. Swipe down from top to bring control center, app crashes

**Comment by ca333** [comment]
thanks for the report - we will fix this.

**Comment by himu007** [comment]
VanncoinsToday at 14:08
Not just control centre but notification centre exits the app as well, so either pulling down from the top or pulling up from the bottom seems to exit the app

**Comment by ca333** [comment]
we re working on the fix already - will notify you upon new release.

**Comment by Kiruel** [comment]
Fixed on master, available next release.

**Comment by tonymorony** [comment]
Let's close it after next release test

**Comment by tonymorony** [comment]
Fixed in 0.1.4
