### ISSUE TITLE
Error after opening app then proceding to trading

### ISSUE THREAD

**Issue by dudezmobi** [KomodoPlatform/atomicDEX#72]
Android device on slow internet

-Currently doing a Trade
-switched between another app
-reopen atomicdex
-open trading menu

this happened

*cannot reproduce issue on IOS

![Screenshot_20190810-005607](https://user-images.githubusercontent.com/37325051/62795696-e43fd880-bb09-11e9-91a0-71f00c2b25ca.png)

**Comment by tonymorony** [comment]
Thank you for report.
What version of the application are you using? @dudezmobi

**Comment by dudezmobi** [comment]
this issue was submitted with 0.1.5 version

**Comment by tonymorony** [comment]
This issue should be not actual on 0.1.6, feel free to re-open issue if it's reproducible on 0.1.6
