### ISSUE TITLE
Orders not shown

### ISSUE THREAD

**Issue by dudezmobi** [KomodoPlatform/atomicDEX#74]
Ver 0.1.6  unfulfilled orders are not displayed. Pending swaps also not displayed.

**Comment by tonymorony** [comment]
Could you please provide a little bit more details please? In what case order is unfulfilled and where it's not displaing? Are you acting as maker or taker? 
Some screenshots might be helpful too.

**Comment by dudezmobi** [comment]
![Screenshot_20190811-060652](https://user-images.githubusercontent.com/37325051/62827298-e20b7600-bbfe-11e9-92e8-90886a1e9c47.png)
![Screenshot_20190811-060657](https://user-images.githubusercontent.com/37325051/62827301-eb94de00-bbfe-11e9-93be-4b50f556ca6c.png)
![Screenshot_20190811-060704](https://user-images.githubusercontent.com/37325051/62827302-f2bbec00-bbfe-11e9-9f67-3157170a4184.png)

Both as a taker or maker. Previous versions does not have this behavior

Steps. 

1. Open atomicdex
2. Create trade
3. Maker or taker
4. Commit trade
5. Press back or left arrow or switch betwern apps during order matching or after first step of swap
6. Look at trade historiy or order ( will not display) but trade appears in history after it has been commited.

**Comment by ca333** [comment]
@dudezmobi manually delete and reinstall the application from playstore
