### ISSUE TITLE
Need to reAdd assets after logging off

### ISSUE THREAD

**Issue by dudezmobi** [KomodoPlatform/atomicDEX#77]
Android 
Version 0.1.6

I got vrsc, eth, kmd, rick, morty on my assets

I logged off then logged in again.

Eth and vrsc disappeared from my assets, i need to readd them again

**Comment by tonymorony** [comment]
Thank you for a report!
There is same https://github.com/KomodoPlatform/atomicDEX/issues/14 feature request, so I close this one.
