### ISSUE TITLE
App randomly crashes (closes) during Syncing

### ISSUE THREAD

**Issue by dudezmobi** [KomodoPlatform/atomicDEX#79]
IOS  
Atomicde
x 0.1.6

App randomly closes during syncing/loading of ETH tx 

![2019-08-23 23 01 45](https://user-images.githubusercontent.com/37325051/63602441-0b160880-c5fa-11e9-9365-32f14392df7f.jpg)

**Comment by tonymorony** [comment]
Can confirm that random crashes in different tx history interaction cases were actual before 0.1.8, now it should be resolved
