### ISSUE TITLE
Swapped asset flashes odd balance

### ISSUE THREAD

**Issue by mammothine** [KomodoPlatform/atomicDEX#8]
Received asset momentarily displays the added total nonconverted balance of sent asset before recalculating to converted and received asset. 

For example, swapped 3 MORTY to receive 1.5 RICK. However RICK balance immediately after confirmed swap displays 3 RICK added to balance (rather than 1.5). Correct, converted balance displays a few seconds later. Able to reproduce. 

iOS 12

**Comment by ca333** [comment]
related to https://github.com/KomodoPlatform/atomicDEX/issues/51
