### ISSUE TITLE
History display wrong

### ISSUE THREAD

**Issue by dudezmobi** [KomodoPlatform/atomicDEX#85]
IOS and android
version 0.1.6

Transaction display error. 
Swap was successful but history displayed it as swap failed.

![2019-09-04 19 34 52](https://user-images.githubusercontent.com/37325051/64251509-4d6d0d00-cf4b-11e9-9d37-a41e87d78114.jpg)
![2019-09-04 19 34 46](https://user-images.githubusercontent.com/37325051/64251510-4fcf6700-cf4b-11e9-82b1-dcb32f995138.jpg)

**Comment by tonymorony** [comment]
As I can see from logs on the seed node this swap was actually failed with ` "type": "MakerPaymentSpendFailed"` error. (https://paste.ubuntu.com/p/Bjvf7jbZJ4/)

Have you actually received the komodo on some point? that's some kind of AtomicDEX-API bug if yes.

Anyway this issue not AtomicDEX GUI related. If you'll face such problem again please reopen this issue and I'll move it to AtomicDEX-API repo.
