### ISSUE TITLE
wallet from assets disappears after update

### ISSUE THREAD

**Issue by dudezmobi** [KomodoPlatform/atomicDEX#86]
ALL platforms
0.1.7

After updating, some coins/wallets randomly disappears (need to add again)

**Comment by tonymorony** [comment]
Hi @dudezmobi Thank you for issue opening. 

Could you please elaborate a little bit: after what actions coins disappears (what are the steps to reproduce the issue)?
Also what do you mean by `ALL platforms`?

Thank you in advance!

**Comment by dudezmobi** [comment]
ios and android

any upgrade version

some previously activated coins becomes deactivated, need re-activate some coins again (but some coins are ok coming from the previous versions)

**Comment by tonymorony** [comment]
Should be fine on 0.1.8
Please re-open with more info and logs if it is reproducible still
