### ISSUE TITLE
[feature request] orderbook page

### ISSUE THREAD

**Issue by ca333** [KomodoPlatform/atomicDEX#87]
Add an orderbook page with all available orders (regardless of balances or activated coins)

**Comment by ca333** [comment]
proposed by jansako:

> Correct me if I am wrong, but currently there is no way of seeing the order book for a coin that the user already does to have a balance in their wallet.
> In a way it is logical, but I would want to know the price before I send any to my DEX wallet... 
> 
> In other words, this is a feature request: Show order books for coins with 0 balance.

**Comment by cipig** [comment]
Orderbook on CLI is visible regardless of the balance of the coin, the coin just has to be enabled.

**Comment by ca333** [comment]
@cipig this is the atomicDEX mobile repo - the above feature request doesn't relate to the atomicDEX-API repo.

**Comment by tonymorony** [comment]
Thats available since 0.2.14
