### ISSUE TITLE
The logs generated by "Send feedback" button should contain flutter logs and swap statuses.

### ISSUE THREAD

**Issue by artemii235** [KomodoPlatform/atomicDEX#91]
Version: 0.1.7-b3cc3b182 Android
Steps to reproduce:
1. Start app, ensure you have swaps in history.
2. Go to settings, click `Send Feedback`.
3. Open resulting file

Expected result: file contains MM2 logs, flutter logs and recent swaps statuses.
Actual result: file contains only MM2 logs, example is attached.
[mm.log](https://github.com/KomodoPlatform/atomicDEX/files/3598994/mm.log)
Having flutter logs and swap statuses will help to troubleshoot failed swaps, especially in cases when status was not broadcasted to seednode for some reason.

**Comment by tonymorony** [comment]
Fixed in 0.1.8
