### ISSUE TITLE
Unable to get past the new seed phrase screen

### ISSUE THREAD

**Issue by me2space** [KomodoPlatform/atomicDEX#92]
On a Samsung Galaxy S8, I'm unable to complete the new wallet creation since it doesn't make it past the new seed phrase screen.  I'm probably unable to scroll to see a button that should let me proceed.

**Comment by tonymorony** [comment]
Hello and thank you for you report! This issue should be fixed in the next application patch which will be released soon

**Comment by tonymorony** [comment]
@me2space should be fixed in 0.1.8 
could you please recheck on your side?

**Comment by me2space** [comment]
It's working. Thank you!

**Comment by tonymorony** [comment]
Glad to hear! Closing the issue as resolved
