### ISSUE TITLE
Pin code and Biometric protection overlap on phones with on-screen fingerscan

### ISSUE THREAD

**Issue by SirSevenG** [KomodoPlatform/atomicDEX#93]
Reproducable on OnePlus 7 Pro, probably other smartphones with on-screen fingerscan.

1. Enable both protection options
2. Close app
3.  Open app
4. Both fingerprint and pin unlock options are presented
5. User can type pin and use application with fingerprint icon displayed

Expected:
 - pin and fingerprint should not be asked at the same time (and overlap in UI)

Video example:
https://drive.google.com/file/d/1-QAJNSmNFasNaVvhtuhBwt_IdXigQeuw/view?usp=sharing

**Comment by bartwr** [comment]
[ @SirSevenG off-topic: What screen recorder app do you use for Android? ]

**Comment by SirSevenG** [comment]
[@bartwr AZ Screen Recorder]

**Comment by tonymorony** [comment]
@SirSevenG Pincode input page was reworked - could you please check if it's actual now on this device?

**Comment by SirSevenG** [comment]
@tonymorony Exact same behavior.
Additional note: on smartphones with dedicated fingerscan (not onscreen one), user will see pin code input page on app start. This way app can be unlocked either with biometrics or correct pin.
Just fingertip icon will not be present in UI, after pincode used.

It's quite arguable topic on how app should behave with both protection options enabled.

**Comment by SirSevenG** [comment]
Not actual anymore.
