### ISSUE TITLE
Withdraw button unresponsive if (amount being withdrawn + custom fee) > (amount available)

### ISSUE THREAD

**Issue by gcharang** [KomodoPlatform/atomicDEX#95]
An error message should be added or the withdrawal amount be adjusted automatically based on the custom fee set
![withdraw-custom-fee](https://user-images.githubusercontent.com/21151592/65618539-18009000-dfdc-11e9-860e-8b1af42740aa.jpg)

**Comment by tonymorony** [comment]
@gcharang Thank you for report! This issue should be resolved in 0.2.0
