### ISSUE TITLE
Portfolio Tab Bugged (v0.2.0)

### ISSUE THREAD

**Issue by whitmorekevinj** [KomodoPlatform/atomicDEX#96]
So I've been using the Android public beta of atomicDEX for about a week. Did my first atomic swap which was neat. 

The issue I'm having is that after the latest update (0.2.0-e634e05ee) my balance is showing as zero and coins/tokens I've added to my portfolio are gone. Trying to add a coin/token again adds an empty space where it should be in the list.

It's probably just a bug with that tab, my transactions are still showing up in my history.

**Comment by tonymorony** [comment]
Thank you for the report! Could you please send the logs (you can get it by "Settings -> Send logs" feature) if this problem is still actual on your side?
Have you tried to restart your app and/or use "Settings -> Logout -> Login" ?

**Comment by whitmorekevinj** [comment]
I did try restarting the app and that didn't help. However logging out and back in seems to have reloaded everything just fine. Thanks!
