### ISSUE TITLE
The password confirmation screen for "Delete Wallet" says "Unlock wallet"

### ISSUE THREAD

**Issue by gcharang** [KomodoPlatform/atomicDEX#97]
The text should mention that the confirmation of Password is needed for deleting the wallet. The current screen is no different from unlocking the wallet for login.

![photo6093677803062012160](https://user-images.githubusercontent.com/21151592/65897041-03513d00-e3cc-11e9-9b49-25d86a937624.jpg)

**Comment by tonymorony** [comment]
This text is correct - you need to use password to unlock (decrypt) your wallet before the deletion.
And after you input the password there is confirmation popup "Are you sure you want to delete your wallet"

**Comment by gcharang** [comment]
Of course the wallet needs to be decrypted before deletion. But the page doesn't signify that entering this password is only one step away from deleting the wallet.

If a user clicks the delete wallet button by mistake, why should a user enter his password without knowing exactly why they are entering it?

Each page should tell the user exactly what its purpose is, so the page that needs password entry for deleting the wallet should at least have the word delete in it.
